### ISSUE TITLE
mkimage-yum.sh from docker upstream

### ISSUE THREAD

**Issue by e-minguez** [cgwalters/centos-dockerbase-minimal#1]
The upstream docker repo contains a [script](https://github.com/docker/docker/blob/master/contrib/mkimage-yum.sh) about how to create a _"yum-based-os"_ image that contains a few rm tricks that maybe can be useful for this proyect.

**Comment by cgwalters** [comment]
Yeah, it may make sense at some point to have this project be in upstream Docker.  I'll adapt a few more of those bits, thanks for the reference!
